# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4668510d817c34ebd8950119074f8ed2562b8d8a959af082ce428d48ff2c7cfae589ed31f980604612c4d1d90ba67e8ad47f1d9cae60b3e198768b97feb73b63

test:
  secret_key_base: e0809ba0c522cfbbc6891f8dde79e4573001c0742f27cad885adf94d0b6ebc3fd9c0d6ecb45614fb917d7a127e4da32a1ee145c32b64f49a5ddc39264fe8bddf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
